In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Input
from keras.optimizers import Adam

In [2]:
df = pd.read_csv(r"C:\Users\VIKASH KUMAR\Downloads\DATA_DUMP\archive (5)\Admission_Predict.csv")

In [3]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [4]:
df.drop(['Serial No.', 'Research'], axis=1, inplace=True)

In [5]:
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Chance of Admit
0,337,118,4,4.5,4.5,9.65,0.92
1,324,107,4,4.0,4.5,8.87,0.76
2,316,104,3,3.0,3.5,8.00,0.72
3,322,110,3,3.5,2.5,8.67,0.80
4,314,103,2,2.0,3.0,8.21,0.65

In [6]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [10]:
model = Sequential([
    Input(shape=(6,)),
    Dense(10, activation='relu'),
    Dense(10, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │            70 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 191 (764.00 B)

 Trainable params: 191 (764.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
x_train.shape

(320, 6)

In [ ]:
model.compile(optimizer=Adam(learning_rate=0.01), loss='mean_squared_error', metrics=['mae'])
import time
start_time = time.time()
history = model.fit(x_train, y_train, epochs=100, batch_size=320, validation_data=(x_test, y_test)) # Batch Gradient Descent and 320 is the total number of samples in the training set
end_time = time.time()
print(f"Training time: {end_time - start_time:.2f} seconds")

Epoch 1/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.0014 - mae: 0.0264 - val_loss: 0.0086 - val_mae: 0.0631
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0017 - mae: 0.0306 - val_loss: 0.0093 - val_mae: 0.0637
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 0.0018 - mae: 0.0302 - val_loss: 0.0087 - val_mae: 0.0620
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 0.0015 - mae: 0.0278 - val_loss: 0.0084 - val_mae: 0.0614
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 0.0016 - mae: 0.0292 - val_loss: 0.0086 - val_mae: 0.0626
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 0.0016 - mae: 0.0300 - val_loss: 0.0088 - val_mae: 0.0637
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0015 - mae: 0.0278 - val_loss: 0.0092 - val_mae: 0.0647
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0015 - mae: 0.0275 - val_loss: 0.0094 - val_mae: 0.0653
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 0.0015 - mae: 0.0277 - val_loss: 0.0094 - val_mae: 0.0656
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 0.0015 - mae: 0.0272 - val_loss: 0.0092 - val_mae: 0.0655
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 0.0014 - mae: 0.0272 - val_loss: 0.0091 - val_mae: 0.0651
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 0.0015 - mae: 0.0280 - val_loss: 0.0090 - val_mae: 0.0645
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - loss: 0.0014 - mae: 0.0277 - val_loss: 0.0089 - val_mae: 0.0639
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 0.0014 - mae: 0.0266 - val_loss: 0.0090 - val_mae: 0.0636
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.0014 - mae: 0.0265 - val_loss: 0.0090 - val_mae: 0.0635
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 0.0014 - mae: 0.0268 - val_loss: 0.0090 - val_mae: 0.0635
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 0.0014 - mae: 0.0268 - val_loss: 0.0089 - val_mae: 0.0636
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0014 - mae: 0.0266 - val_loss: 0.0088 - val_mae: 0.0637
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 0.0014 - mae: 0.0267 - val_loss: 0.0088 - val_mae: 0.0637
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0014 - mae: 0.0267 - val_loss: 0.0088 - val_mae: 0.0637
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 0.0014 - mae: 0.0266 - val_loss: 0.0089 - val_mae: 0.0637
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0014 - mae: 0.0265 - val_loss: 0.0090 - val_mae: 0.0638
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0014 - mae: 0.0265 - val_loss: 0.0090 - val_mae: 0.0639
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0014 - mae: 0.0264 - val_loss: 0.0090 - val_mae: 0.0639
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.0014 - mae: 0.0262 - val_loss: 0.0090 - val_mae: 0.0639
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 0.0014 - mae: 0.0263 - val_loss: 0.0090 - val_mae: 0.0637
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0014 - mae: 0.0264 - val_loss: 0.0089 - val_mae: 0.0636
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 0.0014 - mae: 0.0263 - val_loss: 0.0089 - val_mae: 0.0635
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0014 - mae: 0.0262 - val_loss: 0.0089 - val_mae: 0.0635
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 0.0014 - mae: 0.0262 - val_loss: 0.0090 - val_mae: 0.0636
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.0014 - mae: 0.0261 - val_loss: 0.0090 - val_mae: 0.0638
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0014 - mae: 0.0260 - val_loss: 0.0090 - val_mae: 0.0639
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0014 - mae: 0.0260 - val_loss: 0.0091 - val_mae: 0.0640
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.0014 - mae: 0.0260 - val_loss: 0.0091 - val_mae: 0.0639
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0014 - mae: 0.0258 - val_loss: 0.0091 - val_mae: 0.0637
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 0.0014 - mae: 0.0258 - val_loss: 0.0091 - val_mae: 0.0637
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0014 - mae: 0.0258 - val_loss: 0.0090 - val_mae: 0.0639
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0013 - mae: 0.0259 - val_loss: 0.0090 - val_mae: 0.0641
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0013 - mae: 0.0260 - val_loss: 0.0090 - val_mae: 0.0643
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0013 - mae: 0.0260 - val_loss: 0.0091 - val_mae: 0.0643
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.0013 - mae: 0.0259 - val_loss: 0.0091 - val_mae: 0.0641
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0258 - val_loss: 0.0091 - val_mae: 0.0641
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 0.0013 - mae: 0.0257 - val_loss: 0.0091 - val_mae: 0.0641
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0013 - mae: 0.0257 - val_loss: 0.0091 - val_mae: 0.0642
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0013 - mae: 0.0257 - val_loss: 0.0091 - val_mae: 0.0643
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 0.0013 - mae: 0.0257 - val_loss: 0.0092 - val_mae: 0.0644
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0013 - mae: 0.0256 - val_loss: 0.0092 - val_mae: 0.0644
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0256 - val_loss: 0.0092 - val_mae: 0.0645
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0255 - val_loss: 0.0092 - val_mae: 0.0646
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0255 - val_loss: 0.0093 - val_mae: 0.0648
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 0.0013 - mae: 0.0256 - val_loss: 0.0093 - val_mae: 0.0649
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0256 - val_loss: 0.0093 - val_mae: 0.0649
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0013 - mae: 0.0255 - val_loss: 0.0093 - val_mae: 0.0649
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 0.0013 - mae: 0.0255 - val_loss: 0.0093 - val_mae: 0.0649
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0013 - mae: 0.0255 - val_loss: 0.0093 - val_mae: 0.0649
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.0013 - mae: 0.0255 - val_loss: 0.0093 - val_mae: 0.0649
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0013 - mae: 0.0255 - val_loss: 0.0093 - val_mae: 0.0651
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0013 - mae: 0.0255 - val_loss: 0.0094 - val_mae: 0.0653
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0254 - val_loss: 0.0094 - val_mae: 0.0654
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0254 - val_loss: 0.0094 - val_mae: 0.0654
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0254 - val_loss: 0.0094 - val_mae: 0.0653
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0013 - mae: 0.0254 - val_loss: 0.0094 - val_mae: 0.0654
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0013 - mae: 0.0255 - val_loss: 0.0094 - val_mae: 0.0655
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0013 - mae: 0.0254 - val_loss: 0.0094 - val_mae: 0.0656
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 0.0013 - mae: 0.0254 - val_loss: 0.0094 - val_mae: 0.0656
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 0.0013 - mae: 0.0253 - val_loss: 0.0094 - val_mae: 0.0655
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 0.0013 - mae: 0.0253 - val_loss: 0.0094 - val_mae: 0.0655
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 0.0013 - mae: 0.0253 - val_loss: 0.0094 - val_mae: 0.0655
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0253 - val_loss: 0.0095 - val_mae: 0.0656
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 0.0013 - mae: 0.0253 - val_loss: 0.0095 - val_mae: 0.0659
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0013 - mae: 0.0253 - val_loss: 0.0095 - val_mae: 0.0660
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0253 - val_loss: 0.0095 - val_mae: 0.0660
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0253 - val_loss: 0.0095 - val_mae: 0.0660
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0013 - mae: 0.0253 - val_loss: 0.0095 - val_mae: 0.0660
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0252 - val_loss: 0.0095 - val_mae: 0.0660
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.0013 - mae: 0.0252 - val_loss: 0.0095 - val_mae: 0.0661
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0252 - val_loss: 0.0096 - val_mae: 0.0662
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0013 - mae: 0.0252 - val_loss: 0.0096 - val_mae: 0.0663
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0013 - mae: 0.0253 - val_loss: 0.0096 - val_mae: 0.0662
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0013 - mae: 0.0252 - val_loss: 0.0096 - val_mae: 0.0663
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 0.0013 - mae: 0.0251 - val_loss: 0.0096 - val_mae: 0.0664
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0013 - mae: 0.0251 - val_loss: 0.0096 - val_mae: 0.0664
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0013 - mae: 0.0251 - val_loss: 0.0096 - val_mae: 0.0663
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0251 - val_loss: 0.0096 - val_mae: 0.0663
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 0.0013 - mae: 0.0252 - val_loss: 0.0096 - val_mae: 0.0665
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.0013 - mae: 0.0252 - val_loss: 0.0096 - val_mae: 0.0667
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0252 - val_loss: 0.0097 - val_mae: 0.0668
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0013 - mae: 0.0251 - val_loss: 0.0097 - val_mae: 0.0667
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0013 - mae: 0.0251 - val_loss: 0.0096 - val_mae: 0.0666
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0013 - mae: 0.0251 - val_loss: 0.0097 - val_mae: 0.0665
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 0.0013 - mae: 0.0251 - val_loss: 0.0097 - val_mae: 0.0667
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 0.0013 - mae: 0.0251 - val_loss: 0.0097 - val_mae: 0.0668
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0013 - mae: 0.0250 - val_loss: 0.0097 - val_mae: 0.0669
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 0.0013 - mae: 0.0250 - val_loss: 0.0097 - val_mae: 0.0669
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0013 - mae: 0.0250 - val_loss: 0.0097 - val_mae: 0.0669
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0250 - val_loss: 0.0097 - val_mae: 0.0669
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0013 - mae: 0.0250 - val_loss: 0.0098 - val_mae: 0.0671
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0013 - mae: 0.0250 - val_loss: 0.0098 - val_mae: 0.0673
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 0.0013 - mae: 0.0250 - val_loss: 0.0098 - val_mae: 0.0674
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0013 - mae: 0.0250 - val_loss: 0.0098 - val_mae: 0.0673
Training time: 10.10 seconds

In [17]:
model.compile(optimizer=Adam(learning_rate=0.01), loss='mean_squared_error', metrics=['mae'])
import time
start_time = time.time()
history = model.fit(x_train, y_train, epochs=100, batch_size=1, validation_data=(x_test, y_test)) # Stochastic Gradient Descent
end_time = time.time()
print(f"Training time: {end_time - start_time:.2f} seconds")

Epoch 1/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0055 - mae: 0.0541 - val_loss: 0.0062 - val_mae: 0.0521
Epoch 2/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0039 - mae: 0.0458 - val_loss: 0.0055 - val_mae: 0.0520
Epoch 3/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0039 - mae: 0.0466 - val_loss: 0.0060 - val_mae: 0.0508
Epoch 4/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0041 - mae: 0.0472 - val_loss: 0.0054 - val_mae: 0.0534
Epoch 5/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0040 - mae: 0.0478 - val_loss: 0.0079 - val_mae: 0.0579
Epoch 6/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0039 - mae: 0.0469 - val_loss: 0.0061 - val_mae: 0.0515
Epoch 7/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0038 - mae: 0.0454 - val_loss: 0.0063 - val_mae: 0.0542
Epoch 8/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0041 - mae: 0.0482 - val_loss: 0.0060 - val_mae: 0.0539
Epoch 9/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0050 - mae: 0.0520 - val_loss: 0.0076 - val_mae: 0.0586
Epoch 10/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0043 - mae: 0.0478 - val_loss: 0.0065 - val_mae: 0.0652
Epoch 11/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0040 - mae: 0.0476 - val_loss: 0.0062 - val_mae: 0.0560
Epoch 12/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0038 - mae: 0.0429 - val_loss: 0.0047 - val_mae: 0.0531
Epoch 13/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0039 - mae: 0.0450 - val_loss: 0.0044 - val_mae: 0.0502
Epoch 14/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0038 - mae: 0.0456 - val_loss: 0.0055 - val_mae: 0.0479
Epoch 15/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0035 - mae: 0.0438 - val_loss: 0.0054 - val_mae: 0.0524
Epoch 16/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0037 - mae: 0.0456 - val_loss: 0.0039 - val_mae: 0.0480
Epoch 17/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0038 - mae: 0.0451 - val_loss: 0.0055 - val_mae: 0.0500
Epoch 18/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0034 - mae: 0.0430 - val_loss: 0.0070 - val_mae: 0.0543
Epoch 19/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0035 - mae: 0.0437 - val_loss: 0.0056 - val_mae: 0.0501
Epoch 20/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0036 - mae: 0.0445 - val_loss: 0.0058 - val_mae: 0.0526
Epoch 21/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0035 - mae: 0.0442 - val_loss: 0.0081 - val_mae: 0.0591
Epoch 22/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0036 - mae: 0.0433 - val_loss: 0.0071 - val_mae: 0.0556
Epoch 23/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0035 - mae: 0.0431 - val_loss: 0.0055 - val_mae: 0.0511
Epoch 24/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0035 - mae: 0.0427 - val_loss: 0.0085 - val_mae: 0.0579
Epoch 25/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0038 - mae: 0.0453 - val_loss: 0.0058 - val_mae: 0.0582
Epoch 26/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0041 - mae: 0.0491 - val_loss: 0.0052 - val_mae: 0.0529
Epoch 27/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0037 - mae: 0.0447 - val_loss: 0.0048 - val_mae: 0.0539
Epoch 28/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0037 - mae: 0.0447 - val_loss: 0.0065 - val_mae: 0.0554
Epoch 29/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0037 - mae: 0.0444 - val_loss: 0.0053 - val_mae: 0.0503
Epoch 30/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0038 - mae: 0.0447 - val_loss: 0.0060 - val_mae: 0.0647
Epoch 31/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0039 - mae: 0.0453 - val_loss: 0.0058 - val_mae: 0.0545
Epoch 32/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0037 - mae: 0.0453 - val_loss: 0.0078 - val_mae: 0.0592
Epoch 33/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0037 - mae: 0.0455 - val_loss: 0.0057 - val_mae: 0.0601
Epoch 34/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0034 - mae: 0.0429 - val_loss: 0.0060 - val_mae: 0.0525
Epoch 35/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0034 - mae: 0.0437 - val_loss: 0.0064 - val_mae: 0.0543
Epoch 36/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0034 - mae: 0.0430 - val_loss: 0.0050 - val_mae: 0.0497
Epoch 37/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0035 - mae: 0.0440 - val_loss: 0.0051 - val_mae: 0.0509
Epoch 38/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0034 - mae: 0.0435 - val_loss: 0.0063 - val_mae: 0.0583
Epoch 39/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0035 - mae: 0.0440 - val_loss: 0.0051 - val_mae: 0.0552
Epoch 40/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0034 - mae: 0.0426 - val_loss: 0.0053 - val_mae: 0.0527
Epoch 41/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0035 - mae: 0.0437 - val_loss: 0.0053 - val_mae: 0.0506
Epoch 42/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0035 - mae: 0.0432 - val_loss: 0.0054 - val_mae: 0.0495
Epoch 43/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0034 - mae: 0.0423 - val_loss: 0.0085 - val_mae: 0.0621
Epoch 44/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0039 - mae: 0.0444 - val_loss: 0.0064 - val_mae: 0.0518
Epoch 45/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0037 - mae: 0.0449 - val_loss: 0.0058 - val_mae: 0.0518
Epoch 46/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0034 - mae: 0.0429 - val_loss: 0.0059 - val_mae: 0.0509
Epoch 47/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0032 - mae: 0.0421 - val_loss: 0.0066 - val_mae: 0.0526
Epoch 48/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0034 - mae: 0.0421 - val_loss: 0.0048 - val_mae: 0.0520
Epoch 49/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0032 - mae: 0.0433 - val_loss: 0.0060 - val_mae: 0.0532
Epoch 50/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0032 - mae: 0.0424 - val_loss: 0.0069 - val_mae: 0.0582
Epoch 51/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0032 - mae: 0.0420 - val_loss: 0.0080 - val_mae: 0.0599
Epoch 52/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0034 - mae: 0.0433 - val_loss: 0.0062 - val_mae: 0.0552
Epoch 53/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0039 - mae: 0.0462 - val_loss: 0.0051 - val_mae: 0.0506
Epoch 54/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0034 - mae: 0.0429 - val_loss: 0.0053 - val_mae: 0.0499
Epoch 55/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0031 - mae: 0.0422 - val_loss: 0.0062 - val_mae: 0.0521
Epoch 56/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0034 - mae: 0.0448 - val_loss: 0.0070 - val_mae: 0.0554
Epoch 57/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0032 - mae: 0.0426 - val_loss: 0.0052 - val_mae: 0.0486
Epoch 58/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0031 - mae: 0.0412 - val_loss: 0.0068 - val_mae: 0.0541
Epoch 59/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0033 - mae: 0.0428 - val_loss: 0.0077 - val_mae: 0.0616
Epoch 60/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0033 - mae: 0.0427 - val_loss: 0.0059 - val_mae: 0.0535
Epoch 61/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0032 - mae: 0.0430 - val_loss: 0.0055 - val_mae: 0.0531
Epoch 62/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0035 - mae: 0.0449 - val_loss: 0.0080 - val_mae: 0.0566
Epoch 63/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0036 - mae: 0.0446 - val_loss: 0.0061 - val_mae: 0.0545
Epoch 64/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0049 - mae: 0.0449 - val_loss: 0.0065 - val_mae: 0.0604
Epoch 65/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0031 - mae: 0.0419 - val_loss: 0.0056 - val_mae: 0.0518
Epoch 66/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0036 - mae: 0.0444 - val_loss: 0.0064 - val_mae: 0.0580
Epoch 67/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0033 - mae: 0.0425 - val_loss: 0.0057 - val_mae: 0.0537
Epoch 68/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0031 - mae: 0.0414 - val_loss: 0.0062 - val_mae: 0.0551
Epoch 69/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0031 - mae: 0.0420 - val_loss: 0.0065 - val_mae: 0.0603
Epoch 70/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0033 - mae: 0.0437 - val_loss: 0.0085 - val_mae: 0.0634
Epoch 71/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0040 - mae: 0.0461 - val_loss: 0.0078 - val_mae: 0.0569
Epoch 72/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0031 - mae: 0.0419 - val_loss: 0.0068 - val_mae: 0.0575
Epoch 73/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0036 - mae: 0.0466 - val_loss: 0.0064 - val_mae: 0.0535
Epoch 74/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0031 - mae: 0.0423 - val_loss: 0.0071 - val_mae: 0.0589
Epoch 75/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0033 - mae: 0.0425 - val_loss: 0.0068 - val_mae: 0.0589
Epoch 76/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0032 - mae: 0.0419 - val_loss: 0.0064 - val_mae: 0.0580
Epoch 77/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0035 - mae: 0.0448 - val_loss: 0.0055 - val_mae: 0.0543
Epoch 78/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0033 - mae: 0.0423 - val_loss: 0.0051 - val_mae: 0.0529
Epoch 79/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0030 - mae: 0.0404 - val_loss: 0.0066 - val_mae: 0.0624
Epoch 80/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0033 - mae: 0.0433 - val_loss: 0.0055 - val_mae: 0.0541
Epoch 81/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0036 - mae: 0.0440 - val_loss: 0.0073 - val_mae: 0.0587
Epoch 82/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0032 - mae: 0.0432 - val_loss: 0.0064 - val_mae: 0.0534
Epoch 83/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0032 - mae: 0.0421 - val_loss: 0.0062 - val_mae: 0.0529
Epoch 84/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0034 - mae: 0.0435 - val_loss: 0.0063 - val_mae: 0.0537
Epoch 85/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0031 - mae: 0.0412 - val_loss: 0.0063 - val_mae: 0.0522
Epoch 86/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0030 - mae: 0.0406 - val_loss: 0.0081 - val_mae: 0.0679
Epoch 87/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0033 - mae: 0.0430 - val_loss: 0.0064 - val_mae: 0.0571
Epoch 88/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0031 - mae: 0.0410 - val_loss: 0.0082 - val_mae: 0.0623
Epoch 89/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0034 - mae: 0.0445 - val_loss: 0.0050 - val_mae: 0.0557
Epoch 90/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0034 - mae: 0.0429 - val_loss: 0.0072 - val_mae: 0.0562
Epoch 91/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0032 - mae: 0.0427 - val_loss: 0.0072 - val_mae: 0.0570
Epoch 92/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0031 - mae: 0.0417 - val_loss: 0.0058 - val_mae: 0.0546
Epoch 93/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0029 - mae: 0.0406 - val_loss: 0.0109 - val_mae: 0.0707
Epoch 94/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0034 - mae: 0.0452 - val_loss: 0.0056 - val_mae: 0.0522
Epoch 95/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0034 - mae: 0.0428 - val_loss: 0.0063 - val_mae: 0.0589
Epoch 96/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0029 - mae: 0.0411 - val_loss: 0.0061 - val_mae: 0.0598
Epoch 97/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0032 - mae: 0.0421 - val_loss: 0.0063 - val_mae: 0.0574
Epoch 98/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0031 - mae: 0.0430 - val_loss: 0.0084 - val_mae: 0.0624
Epoch 99/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0032 - mae: 0.0423 - val_loss: 0.0067 - val_mae: 0.0584
Epoch 100/100
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0031 - mae: 0.0418 - val_loss: 0.0072 - val_mae: 0.0592
Training time: 52.44 seconds